#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'postgresql',
  :git => 'https://github.com/phlipper/chef-postgresql'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm', 
  :ref => 'v0.9.0'
