#!/bin/sh
if [ -d /usr/share/rbenv/shims ]; then
  export PATH=/usr/share/rbenv/shims:$PATH
  export RBENV_VERSION="1.9.3-p231-tcs-github"
fi

set -x
git log -n 1 HEAD | cat
ruby -v
bundle -v
set +x

export RACK_ENV=test
export RAILS_ENV=test

script/bootstrap
bundle exec rake db:migrate
bundle exec rake assets:precompile
bundle exec rspec spec
bundle exec rubocop
